# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 22.x, 24.x]


    runs-on: ${{ matrix.os }}

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Init a hexo site
      run: |
        npm i hexo -g
        hexo init
        
    - name: Install node modules
      run: |
        npm install
        npm install hexo-renderer-pug
    
    - name: Checkout hexo-theme-yuzu
      uses: actions/checkout@v4
      with:
        path: themes/hexo-theme-yuzu
  
    - name: Modify _config.yml
      run: |
        sed -i 's_^theme:.*$_theme: hexo-theme-yuzu_' _config.yml
        cat themes/hexo-theme-yuzu/_root_config_example.yml >> _config.yml

    - name: Build assets
      run: npm run build
